[package]
name = "private-channel-metrics"
version.workspace = true
edition.workspace = true

[dependencies]
axum = { workspace = true }
hyper = { workspace = true }
hyper-util = { workspace = true }
prometheus = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tower = { workspace = true, features = ["util"] }
tracing = { workspace = true }

[dev-dependencies]
reqwest = { workspace = true }
